version: "2"
services:
  carbon:
    build: carbon-cache/
    image: 0x20h/carbon-cache
    volumes:
      - whisper:/whisper:rw
  relay:
    build: carbon-relay/
    image: 0x20h/carbon-relay
    environment:
      RELAY_HOSTS: "carbon:2004"
    ports:
      - "2013:2013"
      - "2014:2014"
    depends_on:
      - carbon
  web:
    build: graphite-web/
    image: 0x20h/graphite-web
    volumes:
      - whisper:/whisper:rw
    ports:
      - "8081:8080"
    depends_on:
      - carbon

volumes:
  whisper:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=100m,uid=1000
